version: '3.8'
services:

  db:
    image: postgres:15.3
    container_name: test_task_db
    restart: no
    volumes:
      - ./init_migration.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - ./secrets/db_credentials.env
    command: ["postgres", "-c", "log_statement=all"]

  test-task-service:
    container_name: test_task_application
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    depends_on:
      - "db"
    environment:
      RUN_TESTS: "True"
    env_file:
      - ./secrets/db_credentials.env
    ports:
      - "8080:8080"
